Update bin/compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -29,6 +29,8 @@ for DIR in $CACHED_DIRS; do
   if [ -d $CACHE_DIR/$DIR ]; then
     mkdir -p $DIR
     cp -r $CACHE_DIR/$DIR/.  $DIR
+    echo "-----> Dropping ivy cache from the slug" 
+    rm -rf $SBT_USER_HOME/.ivy2
   fi
 done
 
@@ -114,6 +116,15 @@ mkdir -p "$SBT_USER_HOME/.sbt/plugins" && curl --silent --max-time 10 --location
 HEROKU_PLUGINS_CONFIG="heroku-plugins-$SBT_VERSION.sbt"
 mkdir -p "$SBT_USER_HOME/.sbt/plugins" && curl --silent --max-time 10 --location "http://s3.amazonaws.com/heroku-jvm-langpack-scala/$HEROKU_PLUGINS_CONFIG"  --output "$SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGINS_CONFIG"
 #echo " done"
+
+# build app
+echo "-----> Running: sbt $SBT_TASKS"
+test -e "$SBT_BINDIR"/sbt.boot.properties && PROPS_OPTION="-Dsbt.boot.properties=$SBT_BINDIR/sbt.boot.properties"
+HOME="$SBT_USER_HOME_ABSOLUTE" java -Xmx512M -Dfile.encoding=UTF8 -Duser.home="$SBT_USER_HOME_ABSOLUTE" -Divy.default.ivy.user.dir="$SBT_USER_HOME_ABSOLUTE/.ivy2" $PROPS_OPTION -jar "$SBT_BINDIR"/$SBT_JAR $SBT_TASKS 2>&1 | sed -u 's/^/       /'
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+  echo " !     Failed to build app with SBT $SBT_VERSION"
+  exit 1
+fi
 
 # build app
 echo "-----> Running: sbt $SBT_TASKS"
